coverage: true
corpusDir: "echidna/echidna-corpus"
testMode: assertion
testLimit: 100000
codeSize: 0xffffff
deployer: "0x10000"
sender: ["0x10000"]
workers: 16

# Skip compiling. Repo must be compiled before running Echidna.
cryticArgs: ["--ignore-compile"]
