[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
fs_permissions = [
	{ access = "read", path = "./deployments" },
	{ access = "read", path = "./out" },
]
solc = '0.8.20'
ffi = true
evm_version = "shanghai"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
ignore = [ "src/deps/**/*", "src/interfaces/deps/**/*" ]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }
