[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
	{ access = "read", path = "./deployments"},
	{ access = "read", path = "./out"}
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"