name: Docs

on:
  push:
    branches: [master]

env:
  FOUNDRY_PROFILE: ci
  NODE_VERSION: 18.16.1
  PYTHON_VERSION: 3.9.17

jobs:
  deploy:
    name: Deploy forge doc to GitHub Pages
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Base setup
        uses: ./.github/actions/base-setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build forge docs
        run: forge doc --build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "docs/book"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
